/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  VIEW_TYPE_TODO: () => VIEW_TYPE_TODO,
  default: () => SimpleTodoPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = { todos: [], trash: [], boardZones: [] };
var VIEW_TYPE_TODO = "simple-todo-view";
var PRIORITY_LABELS = { high: "\u9AD8", medium: "\u4E2D", low: "\u4F4E" };
var PRIORITY_ORDER = { high: 0, medium: 1, low: 2 };
function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
}
function formatDueDate(dateStr) {
  if (!dateStr)
    return "";
  const today = (0, import_obsidian.moment)().startOf("day");
  const due = (0, import_obsidian.moment)(dateStr, "YYYY-MM-DD");
  const diff = due.diff(today, "days");
  if (diff < 0)
    return `\u903E\u671F ${Math.abs(diff)} \u5929`;
  if (diff === 0)
    return "\u4ECA\u5929";
  if (diff === 1)
    return "\u660E\u5929";
  if (diff <= 7)
    return `${diff} \u5929\u540E`;
  return due.format("MM/DD");
}
function isDueSoon(dateStr) {
  if (!dateStr)
    return false;
  return (0, import_obsidian.moment)(dateStr, "YYYY-MM-DD").diff((0, import_obsidian.moment)().startOf("day"), "days") <= 1;
}
function isOverdue(dateStr) {
  if (!dateStr)
    return false;
  return (0, import_obsidian.moment)(dateStr, "YYYY-MM-DD").diff((0, import_obsidian.moment)().startOf("day"), "days") < 0;
}
function formatZoneHeader(zone) {
  if (zone.label)
    return zone.label;
  const diff = (0, import_obsidian.moment)(zone.date, "YYYY-MM-DD").diff((0, import_obsidian.moment)().startOf("day"), "days");
  if (diff === 0)
    return "\u4ECA\u5929";
  if (diff === 1)
    return "\u660E\u5929";
  if (diff === -1)
    return "\u6628\u5929";
  if (diff > 1 && diff <= 6)
    return (0, import_obsidian.moment)(zone.date, "YYYY-MM-DD").format("ddd");
  return (0, import_obsidian.moment)(zone.date, "YYYY-MM-DD").format("M\u6708D\u65E5");
}
function logError(message, error) {
  console.error(message, error);
}
function loadSavedSettings(data) {
  const saved = data && typeof data === "object" ? data : {};
  return {
    todos: Array.isArray(saved.todos) ? saved.todos : [],
    trash: Array.isArray(saved.trash) ? saved.trash : [],
    boardZones: Array.isArray(saved.boardZones) ? saved.boardZones : []
  };
}
var TodoModal = class extends import_obsidian.Modal {
  constructor(app, item, onSubmit, isEdit = false) {
    super(app);
    this.item = { ...item };
    this.onSubmit = onSubmit;
    this.isEdit = isEdit;
  }
  onOpen() {
    var _a, _b, _c;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("todo-modal");
    contentEl.createEl("h2", { text: this.isEdit ? "\u7F16\u8F91\u4E8B\u9879" : "\u65B0\u5EFA\u4E8B\u9879", cls: "todo-modal-title" });
    const mkField = (label) => {
      const w = contentEl.createDiv("todo-modal-field");
      w.createEl("label", { text: label, cls: "todo-modal-label" });
      return w;
    };
    const titleInput = mkField("\u4E8B\u9879\u5185\u5BB9").createEl("input", {
      type: "text",
      cls: "todo-modal-input",
      placeholder: "\u8981\u505A\u4EC0\u4E48\uFF1F"
    });
    titleInput.value = (_a = this.item.title) != null ? _a : "";
    titleInput.focus();
    const noteInput = mkField("\u5907\u6CE8\uFF08\u53EF\u9009\uFF09").createEl("textarea", {
      cls: "todo-modal-textarea",
      placeholder: "\u6DFB\u52A0\u5907\u6CE8..."
    });
    noteInput.value = (_b = this.item.note) != null ? _b : "";
    const dateInput = mkField("\u622A\u6B62\u65E5\u671F\uFF08\u53EF\u9009\uFF09").createEl("input", { type: "date", cls: "todo-modal-input" });
    dateInput.value = (_c = this.item.dueDate) != null ? _c : "";
    const prioSelect = mkField("\u4F18\u5148\u7EA7").createEl("select", { cls: "todo-modal-select" });
    ["high", "medium", "low"].forEach((p) => {
      var _a2;
      const opt = prioSelect.createEl("option", { value: p, text: PRIORITY_LABELS[p] });
      if (((_a2 = this.item.priority) != null ? _a2 : "medium") === p)
        opt.selected = true;
    });
    const btnRow = contentEl.createDiv("todo-modal-buttons");
    btnRow.createEl("button", { text: "\u53D6\u6D88", cls: "todo-modal-btn todo-modal-btn-cancel" }).addEventListener("click", () => this.close());
    const submit = () => {
      const title = titleInput.value.trim();
      if (!title) {
        titleInput.addClass("todo-input-error");
        titleInput.focus();
        return;
      }
      this.onSubmit({ title, note: noteInput.value.trim(), dueDate: dateInput.value || null, priority: prioSelect.value });
      this.close();
    };
    btnRow.createEl("button", { text: this.isEdit ? "\u4FDD\u5B58" : "\u6DFB\u52A0", cls: "todo-modal-btn todo-modal-btn-submit" }).addEventListener("click", submit);
    titleInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        submit();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ZoneModal = class extends import_obsidian.Modal {
  constructor(app, zone, onSubmit, isEdit = false) {
    super(app);
    this.zone = { ...zone };
    this.onSubmit = onSubmit;
    this.isEdit = isEdit;
  }
  onOpen() {
    var _a, _b;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("todo-modal");
    contentEl.createEl("h2", { text: this.isEdit ? "\u7F16\u8F91\u5206\u533A" : "\u65B0\u5EFA\u5206\u533A", cls: "todo-modal-title" });
    const mkField = (label) => {
      const w = contentEl.createDiv("todo-modal-field");
      w.createEl("label", { text: label, cls: "todo-modal-label" });
      return w;
    };
    const dateInput = mkField("\u65E5\u671F").createEl("input", { type: "date", cls: "todo-modal-input" });
    dateInput.value = (_a = this.zone.date) != null ? _a : (0, import_obsidian.moment)().format("YYYY-MM-DD");
    dateInput.focus();
    const labelInput = mkField("\u81EA\u5B9A\u4E49\u6807\u9898\uFF08\u53EF\u9009\uFF09").createEl("input", {
      type: "text",
      cls: "todo-modal-input",
      placeholder: "\u7559\u7A7A\u5219\u81EA\u52A8\u663E\u793A\u65E5\u671F"
    });
    labelInput.value = (_b = this.zone.label) != null ? _b : "";
    const btnRow = contentEl.createDiv("todo-modal-buttons");
    btnRow.createEl("button", { text: "\u53D6\u6D88", cls: "todo-modal-btn todo-modal-btn-cancel" }).addEventListener("click", () => this.close());
    const submit = () => {
      if (!dateInput.value) {
        dateInput.addClass("todo-input-error");
        dateInput.focus();
        return;
      }
      this.onSubmit({ date: dateInput.value, label: labelInput.value.trim() });
      this.close();
    };
    btnRow.createEl("button", { text: this.isEdit ? "\u4FDD\u5B58" : "\u521B\u5EFA", cls: "todo-modal-btn todo-modal-btn-submit" }).addEventListener("click", submit);
    dateInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        submit();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var TodoView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.activeTab = "main";
    this.searchQuery = "";
    // cached DOM refs for partial refresh
    this.todoListEl = null;
    this.boardGridEl = null;
    this.trashBodyEl = null;
    // drag: task into zone
    this.dragTaskId = null;
    this.dragTaskSourceZoneId = null;
    // drag: zone reorder
    this.dragZoneId = null;
    this.dragZoneOverId = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_TODO;
  }
  getDisplayText() {
    return "\u5F85\u529E\u6E05\u5355";
  }
  getIcon() {
    return "check-square";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  // ── Full render (called on tab switch / init) ────────────────────────────────
  render() {
    const root = this.containerEl.children[1];
    root.empty();
    root.addClass("todo-root");
    this.renderTopBar(root);
    if (this.activeTab === "main") {
      const body = root.createDiv("todo-main-body");
      this.renderTodoPanel(body);
      this.renderBoardPanel(body);
    } else {
      this.renderTrashPanel(root);
    }
  }
  // ── Partial refresh: only re-render list contents, keep search focus ─────────
  refreshLists() {
    if (this.activeTab === "main") {
      if (this.todoListEl) {
        this.todoListEl.empty();
        this.fillTodoList(this.todoListEl);
      }
      if (this.boardGridEl) {
        this.boardGridEl.empty();
        this.fillBoardGrid(this.boardGridEl);
      }
    } else {
      if (this.trashBodyEl) {
        this.trashBodyEl.empty();
        this.fillTrashBody(this.trashBodyEl);
      }
    }
  }
  // ── Top bar ─────────────────────────────────────────────────────────────────
  renderTopBar(parent) {
    const bar = parent.createDiv("todo-topbar");
    const tabs = bar.createDiv("todo-tabs");
    tabs.createEl("button", {
      text: "\u5F85\u529E & \u89C4\u5212",
      cls: `todo-tab ${this.activeTab === "main" ? "todo-tab-active" : ""}`
    }).addEventListener("click", () => {
      this.activeTab = "main";
      this.render();
    });
    tabs.createEl("button", {
      text: `\u5DF2\u5B8C\u6210 (${this.plugin.settings.trash.length})`,
      cls: `todo-tab ${this.activeTab === "trash" ? "todo-tab-active" : ""}`
    }).addEventListener("click", () => {
      this.activeTab = "trash";
      this.render();
    });
    const right = bar.createDiv("todo-topbar-right");
    if (this.activeTab === "main") {
      right.createEl("button", { cls: "todo-add-btn", text: "+ \u4EFB\u52A1" }).addEventListener("click", () => this.openAddTaskModal());
      right.createEl("button", { cls: "todo-add-zone-btn", text: "+ \u5206\u533A" }).addEventListener("click", () => this.openAddZoneModal());
    }
    const searchInput = right.createEl("input", {
      type: "text",
      cls: "todo-search-input",
      placeholder: "\u641C\u7D22..."
    });
    searchInput.value = this.searchQuery;
    searchInput.addEventListener("input", () => {
      this.searchQuery = searchInput.value;
      this.refreshLists();
    });
  }
  // ── Left panel: todo list ────────────────────────────────────────────────────
  renderTodoPanel(parent) {
    const panel = parent.createDiv("todo-panel");
    panel.createEl("div", { text: "\u5F85\u529E\u4E8B\u9879", cls: "todo-panel-title" });
    panel.addEventListener("dragover", (e) => {
      if (this.dragTaskId && this.dragTaskSourceZoneId) {
        e.preventDefault();
        panel.addClass("todo-panel-dragover");
      }
    });
    panel.addEventListener("dragleave", () => panel.removeClass("todo-panel-dragover"));
    panel.addEventListener("drop", (e) => {
      e.preventDefault();
      panel.removeClass("todo-panel-dragover");
      if (this.dragTaskId && this.dragTaskSourceZoneId) {
        const taskId = this.dragTaskId;
        const sourceZoneId = this.dragTaskSourceZoneId;
        void this.removeTaskFromZone(taskId, sourceZoneId).then(() => {
          this.dragTaskId = null;
          this.dragTaskSourceZoneId = null;
        }).catch((error) => logError("Failed to remove task from zone", error));
      }
    });
    const list = panel.createDiv("todo-list");
    this.todoListEl = list;
    this.fillTodoList(list);
  }
  fillTodoList(list) {
    list.empty();
    let items = [...this.plugin.settings.todos];
    if (this.searchQuery) {
      const q = this.searchQuery.toLowerCase();
      items = items.filter((t) => t.title.toLowerCase().includes(q) || t.note.toLowerCase().includes(q));
    }
    items.sort((a, b) => {
      const pd = PRIORITY_ORDER[a.priority] - PRIORITY_ORDER[b.priority];
      if (pd !== 0)
        return pd;
      if (a.dueDate && b.dueDate)
        return a.dueDate.localeCompare(b.dueDate);
      if (a.dueDate)
        return -1;
      if (b.dueDate)
        return 1;
      return a.createdAt.localeCompare(b.createdAt);
    });
    if (items.length === 0) {
      const empty = list.createDiv("todo-empty");
      empty.createEl("div", { text: "\u{1F389}", cls: "todo-empty-icon" });
      empty.createEl("div", { text: this.searchQuery ? "\u6CA1\u6709\u5339\u914D\u7684\u4E8B\u9879" : "\u6682\u65E0\u5F85\u529E\uFF0C\u70B9\u51FB + \u4EFB\u52A1 \u6DFB\u52A0", cls: "todo-empty-text" });
      return;
    }
    items.forEach((item) => this.renderTaskRow(list, item));
  }
  renderTaskRow(parent, item) {
    const inZone = this.plugin.settings.boardZones.some((z) => z.todoIds.includes(item.id));
    const row = parent.createDiv("todo-item");
    row.dataset.id = item.id;
    if (inZone)
      row.addClass("todo-item-in-zone");
    if (isOverdue(item.dueDate))
      row.addClass("todo-item-overdue");
    row.setAttribute("draggable", "true");
    row.addEventListener("dragstart", (e) => {
      this.dragTaskId = item.id;
      this.dragTaskSourceZoneId = null;
      row.addClass("todo-item-dragging");
      if (e.dataTransfer) {
        e.dataTransfer.effectAllowed = "move";
        e.dataTransfer.setData("text/plain", item.id);
      }
    });
    row.addEventListener("dragend", () => row.removeClass("todo-item-dragging"));
    const cb = row.createEl("button", { cls: "todo-checkbox" });
    (0, import_obsidian.setIcon)(cb, "circle");
    cb.addEventListener("click", (e) => {
      e.stopPropagation();
      void this.completeTask(item.id).catch((error) => logError("Failed to complete task", error));
    });
    const content = row.createDiv("todo-item-content");
    if (!inZone) {
      content.createEl("span", { cls: "todo-unplanned-dot", attr: { "aria-label": "\u672A\u89C4\u5212" } });
    }
    const titleRow = content.createDiv("todo-item-title-row");
    titleRow.createEl("span", { text: item.title, cls: "todo-item-title" });
    titleRow.createEl("span", { text: PRIORITY_LABELS[item.priority], cls: `todo-priority-badge todo-priority-${item.priority}` });
    if (item.dueDate || item.note) {
      const meta = content.createDiv("todo-item-meta");
      if (item.dueDate) {
        const cls = isOverdue(item.dueDate) ? "todo-due-overdue" : isDueSoon(item.dueDate) ? "todo-due-soon" : "todo-due-normal";
        meta.createEl("span", { text: `\u{1F4C5} ${formatDueDate(item.dueDate)}`, cls: `todo-due ${cls}` });
      }
      if (item.note)
        meta.createEl("span", { text: item.note, cls: "todo-item-note" });
    }
    const actions = row.createDiv("todo-item-actions");
    actions.createEl("button", { cls: "todo-action-btn", text: "\u270F\uFE0F" }).addEventListener("click", (e) => {
      e.stopPropagation();
      this.openEditTaskModal(item);
    });
    actions.createEl("button", { cls: "todo-action-btn", text: "\u{1F5D1}\uFE0F" }).addEventListener("click", (e) => {
      e.stopPropagation();
      void this.deleteTask(item.id).catch((error) => logError("Failed to delete task", error));
    });
  }
  // ── Right panel: board ───────────────────────────────────────────────────────
  renderBoardPanel(parent) {
    const panel = parent.createDiv("todo-board-panel");
    panel.createEl("div", { text: "\u89C4\u5212\u677F", cls: "todo-panel-title" });
    const grid = panel.createDiv("todo-board-grid");
    this.boardGridEl = grid;
    this.fillBoardGrid(grid);
  }
  fillBoardGrid(grid) {
    grid.empty();
    const zones = [...this.plugin.settings.boardZones].sort((a, b) => a.order - b.order);
    if (zones.length === 0) {
      const empty = grid.createDiv("todo-empty");
      empty.createEl("div", { text: "\u{1F5C2}\uFE0F", cls: "todo-empty-icon" });
      empty.createEl("div", { text: "\u70B9\u51FB\u300C+ \u5206\u533A\u300D\u65B0\u5EFA", cls: "todo-empty-text" });
      return;
    }
    zones.forEach((zone) => this.renderZoneCard(grid, zone));
  }
  renderZoneCard(parent, zone) {
    const today = (0, import_obsidian.moment)().format("YYYY-MM-DD");
    const isPast = zone.date < today;
    const isToday = zone.date === today;
    const card = parent.createDiv("todo-zone-card");
    card.dataset.zoneId = zone.id;
    if (isPast)
      card.addClass("todo-zone-past");
    if (isToday)
      card.addClass("todo-zone-today");
    card.addEventListener("dragover", (e) => {
      e.preventDefault();
      if (this.dragZoneId && this.dragZoneId !== zone.id) {
        this.dragZoneOverId = zone.id;
        card.addClass("todo-zone-card-zone-over");
        if (e.dataTransfer)
          e.dataTransfer.dropEffect = "move";
      } else if (this.dragTaskId) {
        card.addClass("todo-zone-card-dragover");
        if (e.dataTransfer)
          e.dataTransfer.dropEffect = "move";
      }
    });
    card.addEventListener("dragleave", () => {
      card.removeClass("todo-zone-card-dragover");
      card.removeClass("todo-zone-card-zone-over");
      if (this.dragZoneOverId === zone.id)
        this.dragZoneOverId = null;
    });
    card.addEventListener("drop", (e) => {
      e.preventDefault();
      card.removeClass("todo-zone-card-dragover");
      card.removeClass("todo-zone-card-zone-over");
      if (this.dragZoneId && this.dragZoneId !== zone.id) {
        const draggedId = this.dragZoneId;
        void this.reorderZone(draggedId, zone.id).then(() => {
          this.dragZoneId = null;
          this.dragZoneOverId = null;
        }).catch((error) => logError("Failed to reorder zone", error));
      } else if (this.dragTaskId) {
        const taskId = this.dragTaskId;
        const sourceZoneId = this.dragTaskSourceZoneId;
        void this.assignTaskToZone(taskId, sourceZoneId, zone.id).then(() => {
          this.dragTaskId = null;
          this.dragTaskSourceZoneId = null;
        }).catch((error) => logError("Failed to assign task to zone", error));
      }
    });
    const header = card.createDiv("todo-zone-header");
    header.setAttribute("draggable", "true");
    header.addEventListener("dragstart", (e) => {
      this.dragZoneId = zone.id;
      card.addClass("todo-zone-dragging");
      if (e.dataTransfer) {
        e.dataTransfer.effectAllowed = "move";
        e.dataTransfer.setData("text/zone", zone.id);
      }
      e.stopPropagation();
    });
    header.addEventListener("dragend", () => {
      card.removeClass("todo-zone-dragging");
      this.dragZoneId = null;
    });
    const headerLeft = header.createDiv("todo-zone-header-left");
    headerLeft.createEl("div", {
      text: formatZoneHeader(zone),
      cls: "todo-zone-title"
    });
    headerLeft.createEl("div", {
      text: (0, import_obsidian.moment)(zone.date, "YYYY-MM-DD").format("YYYY/M/D"),
      cls: "todo-zone-subtitle"
    });
    const headerRight = header.createDiv("todo-zone-header-right");
    headerRight.createEl("span", {
      text: String(zone.todoIds.filter((id) => this.plugin.settings.todos.find((t) => t.id === id)).length),
      cls: "todo-zone-count"
    });
    headerRight.createEl("button", { cls: "todo-zone-action-btn", text: "\u270F\uFE0F" }).addEventListener("click", (e) => {
      e.stopPropagation();
      this.openEditZoneModal(zone);
    });
    headerRight.createEl("button", { cls: "todo-zone-action-btn todo-zone-delete-btn", text: "\u2715" }).addEventListener("click", (e) => {
      e.stopPropagation();
      void this.deleteZone(zone.id).catch((error) => logError("Failed to delete zone", error));
    });
    const body = card.createDiv("todo-zone-body");
    const assignedTodos = zone.todoIds.map((id) => this.plugin.settings.todos.find((t) => t.id === id)).filter((t) => !!t);
    if (assignedTodos.length === 0) {
      body.createDiv("todo-zone-drop-hint").createEl("span", {
        text: "\u62D6\u5165\u4EFB\u52A1",
        cls: "todo-zone-hint-text"
      });
    } else {
      assignedTodos.forEach((item) => this.renderZoneTaskRow(body, item, zone.id));
    }
  }
  renderZoneTaskRow(parent, item, zoneId) {
    const row = parent.createDiv("todo-zone-item");
    row.dataset.id = item.id;
    row.setAttribute("draggable", "true");
    row.addEventListener("dragstart", (e) => {
      this.dragTaskId = item.id;
      this.dragTaskSourceZoneId = zoneId;
      row.addClass("todo-item-dragging");
      if (e.dataTransfer) {
        e.dataTransfer.effectAllowed = "move";
        e.dataTransfer.setData("text/plain", item.id);
      }
      e.stopPropagation();
    });
    row.addEventListener("dragend", () => row.removeClass("todo-item-dragging"));
    const cb = row.createEl("button", { cls: "todo-checkbox todo-checkbox-sm" });
    (0, import_obsidian.setIcon)(cb, "circle");
    cb.addEventListener("click", (e) => {
      e.stopPropagation();
      void this.completeTask(item.id).catch((error) => logError("Failed to complete task", error));
    });
    const content = row.createDiv("todo-zone-item-content");
    const titleRow = content.createDiv("todo-zone-item-title-row");
    titleRow.createEl("span", { text: item.title, cls: "todo-zone-item-title" });
    titleRow.createEl("span", { text: PRIORITY_LABELS[item.priority], cls: `todo-priority-badge todo-priority-${item.priority}` });
    const dragHint = row.createEl("span", { cls: "todo-zone-drag-hint", text: "\u283F" });
    dragHint.setAttribute("aria-hidden", "true");
  }
  // ── Trash panel ──────────────────────────────────────────────────────────────
  renderTrashPanel(parent) {
    const body = parent.createDiv("todo-body");
    this.trashBodyEl = body;
    this.fillTrashBody(body);
  }
  fillTrashBody(body) {
    body.empty();
    let items = [...this.plugin.settings.trash];
    if (this.searchQuery) {
      const q = this.searchQuery.toLowerCase();
      items = items.filter((t) => t.title.toLowerCase().includes(q) || t.note.toLowerCase().includes(q));
    }
    items.sort((a, b) => {
      var _a, _b;
      return ((_a = b.completedAt) != null ? _a : "").localeCompare((_b = a.completedAt) != null ? _b : "");
    });
    if (items.length === 0) {
      const empty = body.createDiv("todo-empty");
      empty.createEl("div", { text: "\u{1F4ED}", cls: "todo-empty-icon" });
      empty.createEl("div", { text: "\u5DF2\u5B8C\u6210\u7684\u4E8B\u9879\u4F1A\u51FA\u73B0\u5728\u8FD9\u91CC", cls: "todo-empty-text" });
      return;
    }
    const toolbar = body.createDiv("todo-trash-toolbar");
    toolbar.createEl("button", { text: "\u6E05\u7A7A\u5DF2\u5B8C\u6210", cls: "todo-clear-btn" }).addEventListener("click", () => {
      void this.clearTrash().catch((error) => logError("Failed to clear completed tasks", error));
    });
    items.forEach((item) => {
      const row = body.createDiv("todo-item todo-item-done");
      const cb = row.createEl("button", { cls: "todo-checkbox todo-checkbox-done" });
      (0, import_obsidian.setIcon)(cb, "check-circle-2");
      cb.addEventListener("click", (e) => {
        e.stopPropagation();
        void this.restoreTask(item.id).catch((error) => logError("Failed to restore task", error));
      });
      const content = row.createDiv("todo-item-content");
      content.createDiv("todo-item-title-row").createEl("span", { text: item.title, cls: "todo-item-title todo-item-title-done" });
      if (item.completedAt) {
        content.createDiv("todo-item-meta").createEl("span", {
          text: `\u5B8C\u6210\u4E8E ${(0, import_obsidian.moment)(item.completedAt).format("MM/DD HH:mm")}`,
          cls: "todo-completed-at"
        });
      }
      const actions = row.createDiv("todo-item-actions");
      actions.createEl("button", { cls: "todo-action-btn", text: "\u{1F5D1}\uFE0F" }).addEventListener("click", (e) => {
        e.stopPropagation();
        void this.permanentDelete(item.id).catch((error) => logError("Failed to permanently delete task", error));
      });
    });
  }
  // ── Data actions ─────────────────────────────────────────────────────────────
  openAddTaskModal() {
    new TodoModal(this.app, { priority: "medium" }, (data) => {
      var _a, _b, _c;
      this.plugin.settings.todos.unshift({
        id: generateId(),
        title: data.title,
        note: (_a = data.note) != null ? _a : "",
        dueDate: (_b = data.dueDate) != null ? _b : null,
        priority: (_c = data.priority) != null ? _c : "medium",
        completed: false,
        completedAt: null,
        createdAt: new Date().toISOString()
      });
      void this.plugin.saveSettings().then(() => this.render()).catch((error) => logError("Failed to add task", error));
    }).open();
  }
  openEditTaskModal(item) {
    new TodoModal(this.app, item, (data) => {
      var _a, _b, _c;
      const idx = this.plugin.settings.todos.findIndex((t) => t.id === item.id);
      if (idx === -1)
        return;
      this.plugin.settings.todos[idx] = { ...this.plugin.settings.todos[idx], title: data.title, note: (_a = data.note) != null ? _a : "", dueDate: (_b = data.dueDate) != null ? _b : null, priority: (_c = data.priority) != null ? _c : "medium" };
      void this.plugin.saveSettings().then(() => this.render()).catch((error) => logError("Failed to edit task", error));
    }, true).open();
  }
  openAddZoneModal() {
    new ZoneModal(this.app, {}, (data) => {
      var _a;
      const maxOrder = this.plugin.settings.boardZones.reduce((m, z) => Math.max(m, z.order), -1);
      this.plugin.settings.boardZones.push({ id: generateId(), date: data.date, label: (_a = data.label) != null ? _a : "", todoIds: [], order: maxOrder + 1 });
      void this.plugin.saveSettings().then(() => this.render()).catch((error) => logError("Failed to add zone", error));
    }).open();
  }
  openEditZoneModal(zone) {
    new ZoneModal(this.app, zone, (data) => {
      var _a;
      const idx = this.plugin.settings.boardZones.findIndex((z) => z.id === zone.id);
      if (idx === -1)
        return;
      this.plugin.settings.boardZones[idx] = { ...this.plugin.settings.boardZones[idx], date: data.date, label: (_a = data.label) != null ? _a : "" };
      void this.plugin.saveSettings().then(() => this.render()).catch((error) => logError("Failed to edit zone", error));
    }, true).open();
  }
  async deleteZone(zoneId) {
    this.plugin.settings.boardZones = this.plugin.settings.boardZones.filter((z) => z.id !== zoneId);
    await this.plugin.saveSettings();
    this.render();
  }
  async reorderZone(draggedId, targetId) {
    const zones = [...this.plugin.settings.boardZones].sort((a, b) => a.order - b.order);
    const fromIdx = zones.findIndex((z) => z.id === draggedId);
    const toIdx = zones.findIndex((z) => z.id === targetId);
    if (fromIdx === -1 || toIdx === -1)
      return;
    const [moved] = zones.splice(fromIdx, 1);
    zones.splice(toIdx, 0, moved);
    zones.forEach((z, i) => {
      z.order = i;
    });
    this.plugin.settings.boardZones = zones;
    await this.plugin.saveSettings();
    this.render();
  }
  async assignTaskToZone(taskId, sourceZoneId, targetZoneId) {
    if (sourceZoneId === targetZoneId)
      return;
    if (sourceZoneId) {
      const src = this.plugin.settings.boardZones.find((z) => z.id === sourceZoneId);
      if (src)
        src.todoIds = src.todoIds.filter((id) => id !== taskId);
    }
    const target = this.plugin.settings.boardZones.find((z) => z.id === targetZoneId);
    if (target && !target.todoIds.includes(taskId))
      target.todoIds.push(taskId);
    await this.plugin.saveSettings();
    this.render();
  }
  async removeTaskFromZone(taskId, zoneId) {
    const zone = this.plugin.settings.boardZones.find((z) => z.id === zoneId);
    if (zone) {
      zone.todoIds = zone.todoIds.filter((id) => id !== taskId);
    }
    await this.plugin.saveSettings();
    this.render();
  }
  async completeTask(id) {
    this.plugin.settings.boardZones.forEach((z) => {
      z.todoIds = z.todoIds.filter((tid) => tid !== id);
    });
    const idx = this.plugin.settings.todos.findIndex((t) => t.id === id);
    if (idx === -1)
      return;
    const item = this.plugin.settings.todos.splice(idx, 1)[0];
    item.completed = true;
    item.completedAt = new Date().toISOString();
    this.plugin.settings.trash.unshift(item);
    await this.plugin.saveSettings();
    this.render();
  }
  async deleteTask(id) {
    this.plugin.settings.boardZones.forEach((z) => {
      z.todoIds = z.todoIds.filter((tid) => tid !== id);
    });
    const idx = this.plugin.settings.todos.findIndex((t) => t.id === id);
    if (idx === -1)
      return;
    const item = this.plugin.settings.todos.splice(idx, 1)[0];
    item.completed = true;
    item.completedAt = new Date().toISOString();
    this.plugin.settings.trash.unshift(item);
    await this.plugin.saveSettings();
    this.render();
  }
  async restoreTask(id) {
    const idx = this.plugin.settings.trash.findIndex((t) => t.id === id);
    if (idx === -1)
      return;
    const item = this.plugin.settings.trash.splice(idx, 1)[0];
    item.completed = false;
    item.completedAt = null;
    this.plugin.settings.todos.unshift(item);
    await this.plugin.saveSettings();
    this.render();
  }
  async permanentDelete(id) {
    this.plugin.settings.trash = this.plugin.settings.trash.filter((t) => t.id !== id);
    await this.plugin.saveSettings();
    this.render();
  }
  async clearTrash() {
    this.plugin.settings.trash = [];
    await this.plugin.saveSettings();
    this.render();
  }
};
var TodoSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("\u5F85\u529E\u6E05\u5355\u8BBE\u7F6E").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u6570\u636E\u7EDF\u8BA1").setDesc(
      `\u5F85\u529E\uFF1A${this.plugin.settings.todos.length} \u9879 | \u5DF2\u5B8C\u6210\uFF1A${this.plugin.settings.trash.length} \u9879 | \u5206\u533A\uFF1A${this.plugin.settings.boardZones.length} \u4E2A`
    );
    new import_obsidian.Setting(containerEl).setName("\u6E05\u7A7A\u6240\u6709\u6570\u636E").setDesc("\u5220\u9664\u6240\u6709\u5F85\u529E\u3001\u5DF2\u5B8C\u6210\u4E8B\u9879\u548C\u5206\u533A\uFF0C\u4E0D\u53EF\u64A4\u9500\u3002").addButton((btn) => btn.setButtonText("\u6E05\u7A7A").setWarning().onClick(() => {
      this.plugin.settings.todos = [];
      this.plugin.settings.trash = [];
      this.plugin.settings.boardZones = [];
      void this.plugin.saveSettings().then(() => this.display()).catch((error) => logError("Failed to clear settings data", error));
    }));
  }
};
var SimpleTodoPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  onload() {
    void this.loadSettings().then(() => {
      this.registerView(VIEW_TYPE_TODO, (leaf) => new TodoView(leaf, this));
      this.addRibbonIcon("check-square", "\u5F85\u529E\u6E05\u5355", () => {
        void this.activateView().catch((error) => logError("Failed to activate todo view", error));
      });
      this.addCommand({
        id: "open-todo-list",
        name: "\u6253\u5F00\u5F85\u529E\u6E05\u5355",
        callback: () => {
          void this.activateView().catch((error) => logError("Failed to activate todo view", error));
        }
      });
      this.addCommand({
        id: "add-todo-item",
        name: "\u65B0\u5EFA\u5F85\u529E\u4E8B\u9879",
        callback: () => {
          void this.activateView().then(() => {
            var _a;
            const view = (_a = this.app.workspace.getLeavesOfType(VIEW_TYPE_TODO)[0]) == null ? void 0 : _a.view;
            if (view)
              view.openAddTaskModal();
          }).catch((error) => logError("Failed to open add task modal", error));
        }
      });
      this.addSettingTab(new TodoSettingTab(this.app, this));
    }).catch((error) => logError("Failed to load todo plugin", error));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = loadSavedSettings(await this.loadData());
    if (!this.settings.boardZones)
      this.settings.boardZones = [];
    this.settings.boardZones.forEach((z, i) => {
      if (z.order === void 0)
        z.order = i;
    });
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_TODO)[0];
    if (!leaf) {
      leaf = workspace.getLeaf(true);
    }
    await leaf.setViewState({ type: VIEW_TYPE_TODO, active: true });
  }
};
